apiVersion: v1
kind: Pod
metadata:
  name: fsx-share-test
spec:
  containers:
  - name: fsx-share-test
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo  \"hello from FSx\" - $(date -u) >> /fsx-shared/test.txt; sleep 120; done"]
    volumeMounts:
    - name: fsx-pv
      mountPath: /fsx-shared
  volumes:
  - name: fsx-pv
    persistentVolumeClaim:
      claimName: fsx-pvc
