apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <my-p4d-eks-cluster>
  version: "1.31"
  region: us-west-2
  tags:
    karpenter.sh/discovery: awsnemo-p4d-cluster

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  - us-west-2d

managedNodeGroups:

  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  - name: p4d-nodes
    instanceType: p4d.24xlarge
    instancePrefix: p4d-odcr-nodes
    privateNetworking: true
    availabilityZones: ["us-west-2b"]
    efaEnabled: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900

    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
