apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "nemo-p4d-eks-cluster"
  version: "1.31"
  region: us-west-2
  tags:
    karpenter.sh/discovery: awsnemo-p4d-cluster

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c

managedNodeGroups:

  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  - name: p4d-nodes
    instanceType: p4d.24xlarge
    instancePrefix: p4d-odcr-nodes
    privateNetworking: true
    efaEnabled: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::746669208233:role/t2mic_eks_role

vpc:
  subnets:
    private:
      us-west-2a:
        id: "subnet-0111111111111111"
      us-west-2b:
        id: "subnet-0222222222222222"
      us-west-2c:
        id: "subnet-0333333333333333"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
    
