apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv1
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc1
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-088319419f1710873  # from AWS FSx console: File system ID
    volumeAttributes:
      dnsname: fs-088319419f1710873.fsx.us-west-2.amazonaws.com  # from AWS FSx console: DNS name
      mountname: avj4jbev # from AWS FSx console: Mount name
