apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0033845216cbea5a9  # from AWS FSx console: File system ID
    volumeAttributes:
      dnsname: fs-0033845216cbea5a9.fsx.us-west-2.amazonaws.com  # from AWS FSx console: DNS name
      mountname: rmyrpb4v # from AWS FSx console: Mount name
