apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-06f973592c9d23795  # from AWS FSx console: File system ID
    volumeAttributes:
      dnsname: fs-06f973592c9d23795.fsx.us-west-2.amazonaws.com  # from AWS FSx console: DNS name
      mountname: Pnz4xbev # from AWS FSx console: Mount name
